### ISSUE TITLE
Crashes in combination with UIForceTouchCapabilityAvailable

### ISSUE THREAD

**Issue by magnett** [AndreasVerhoeven/AveSimulator3DTouch#2]
Hi!
You have done a great job however there is an issue. I am using in the `cellForItemAtIndexPath` an if statement to determine if the simulator / device supports force touch and handle the peek & pop appropriately.
`if(self.traitCollection.forceTouchCapability == UIForceTouchCapabilityAvailable)
    {
        [self registerForPreviewingWithDelegate:self sourceView:cell];
    }`
This is crashing the app when the simulator version is 8.x.

**Comment by AndreasVerhoeven** [comment]
`forceTouchCapability` does not exist on iOS8, so you'd have to check with a respondsToSelector:

```
if([self.traitCollection respondsToSelector:@selector(forceTouchCapability)] && self.traitCollection.forceTouchCapability == UIForceTouchCapabilityAvailable) {
 [self registerForPreviewingWithDelegate:self sourceView:cell]; 
}
```

**Comment by magnett** [comment]
Thanks for the help. With your code it doesn't crashes, however nothing is visible in my collectionView.

**Comment by AndreasVerhoeven** [comment]
Yes, 3D Touch only works on iOS 9 devices /simulators of course.
